# Generated by Django 5.2.3 on 2025-07-18 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoe',
            old_name='Category',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='shoe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='shoes/'),
        ),
    ]
