# Generated by Django 5.2.3 on 2025-08-04 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_order_status_profile_review_cartitem_wishlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Shoe',
            new_name='shoe',
        ),
    ]
